class GSK:
    class ColName:
        COLOR = 'COLOR'
        DESIGNATION = 'DESIGNATION'
        GSK_DESIGNATION = 'GSK DESIGNATION'
        DATE = 'DATE'
        CODE = 'Code'
        UNIT_SALES = 'SALES UNIT'
        VALUE_SALES = 'SALES VALUE(GBP)'
        SOURCE = 'SOURCE'
        INPUT = 'COLUMN'
        NEW = 'NEW COLUMN'
        GSK = 'GSK'
        ALL = 'ALL'
        SKU = 'SKU'
        SKU_TYPE = 'SKU TYPE'
        SKU_ORDER = 'SKU ORDER'
        SKU_TYPE_ORDER = 'SKU TYPE ORDER'
        PERIOD_TYPE = 'PERIOD_TYPE'
        BRAND = 'BRAND'
        RFC_VALUE_COL = 'RFC VALUE(GBP)'
        RFC_UNIT_COL = 'RFC UNIT'
        RENAMED_COLUMNS = 'RENAMED COLUMNS'
        ACTION = 'ACTION'
        NSP = 'NSP'
        UPDATED_ON = 'LAST UPDATE'
        INPUT_DATA_COLUMNS = [SKU, RFC_VALUE_COL, RFC_UNIT_COL, NSP, UNIT_SALES, VALUE_SALES]

    class Naming:
        END_COL = 'FEU'
        UNNAMED_COLUMN = 'Unnamed'
        TOTAL = 'Total'
        ALL_SKUs = 'ALL'
        SKU_SKU_TYPE = 'SKU'
        SKU_BRAND_SKU_TYPE = 'BRAND - SKU'
        BRAND_SKU_TYPE = 'BRAND'
        WEEK_COL_START = 'W'
        TOTAL_COL_START = 'TOTAL DISPO'
        NSP_COL_START = 'NSP'
        RFC_UNIT_START = 'RFC '
        FORWARD_FILL_ACTION = 'ffill'
        BACKWARD_FILL_ACTION = 'bfill'
        DIFF_ACTION = 'diff'
        ZERO_ACTION = 'zero'
        ZERO_BACKFILL_ACTION = 'zero_bfill'
        SUM_UP_ACTION = 'sum'
        NO_ACTION = 'no action'
        QUARTER_SUM = 'quarter sum'
        PERIOD_TYPE_DAILY = 'DAILY'
        PERIOD_TYPE_Weekly = 'WEEKLY'
        PERIOD_TYPE_MTD = 'MTD'
        PERIOD_TYPE_MONTHLY = 'MONTHLY'
        PERIOD_TYPE_QTD = 'QTD'
        PERIOD_TYPE_STD = 'STD'
        PERIOD_TYPE_YTD = 'YTD'
        GBP = 'GBP'

        SALES_OUTPUT_FILE_NAME = 'GSK SALES.xlsx'


class Parameters:
    class SheetName:
        DESIGNATION = 'DESIGNATIONS'
        COLUMNS = 'COLUMNS'
        ORDER = 'METADATA'
