html.Div(id=IDs.dashboard,
                        style={Naming.display: Naming.flex,
                               Naming.flex_direction: Naming.flex_col,
                               Naming.border: '1px solid black',
                               Naming.padding: '10px',
                               },
                        children=[html.Div('Dashboard',
                                           style={'color': '#fc7b03',
                                                  Naming.height: '10%',
                                                  Naming.border: '1px solid black',
                                                  },
                                           ),
                                  html.Hr(),
                                  html.Br(),
                                  dcc.RadioItems(id=IDs.vol_val_rb,
                                                 style={},
                                                 options=[{'label': 'Value', 'value': sales_as_val},
                                                          {'label': 'Volume', 'value': sales_as_vol},
                                                          ],
                                                 value=sales_as_val
                                                 ),
                                  html.Hr(),
                                  html.Div(title='All periods Overall achievements',
                                           id=IDs.all_periods_overall_achievements,
                                           style={Naming.display: Naming.flex,
                                                  Naming.flex_direction: Naming.flex_row,
                                                  Naming.height: '30%',
                                                  },
                                           children=[html.Label('Month Achievements',
                                                                ),
                                                     dcc.Graph(id=IDs.graph_overall_month_indicator,
                                                               style={Naming.width: '25%',
                                                                      Naming.height: '100%',
                                                                      Naming.padding: '10px',
                                                                      },
                                                               ),
                                                     html.Hr(),
                                                     dcc.Graph(id=IDs.graph_overall_quarter_indicator,
                                                               style={Naming.width: '25%',
                                                                      Naming.height: '100%',
                                                                      Naming.padding: '10px',
                                                                      },
                                                               ),
                                                     html.Hr(),
                                                     dcc.Graph(id=IDs.graph_overall_half_indicator,
                                                               style={Naming.width: '25%',
                                                                      Naming.height: '100%',
                                                                      Naming.padding: '10px',
                                                                      },
                                                               ),
                                                     html.Hr(),
                                                     dcc.Graph(id=IDs.graph_overall_year_indicator,
                                                               style={Naming.width: '25%',
                                                                      Naming.height: '100%',
                                                                      Naming.padding: '10px',
                                                                      },
                                                               ),
                                                     ]
                                           ),
                                  html.Hr(),
                                  html.Br(),
                                  html.Div(style={Naming.display: Naming.flex,
                                                  Naming.flex_direction: Naming.flex_row,
                                                  Naming.height: '60%'
                                                  },
                                           children=[html.Div(title='Parameters',
                                                              id=IDs.parameters,
                                                              style={Naming.width: '15%',
                                                                     },
                                                              children=[html.H3('Parameters'),
                                                                        DashBoard.nav_bar(),
                                                                        ],
                                                              ),
                                                     html.Hr(),
                                                     html.Div(title='Sales Graphs',
                                                              id=IDs.graphs,
                                                              style={Naming.width: '85%',
                                                                     Naming.padding: '10px'},
                                                              children=[html.H3('Sales Graphs'),
                                                                        DashBoard.dash_screens[Naming.gsk_screen].Div,
                                                                        ],
                                                              ),
                                                     ],
                                           ),
                                  ],
                        )